/*
For this exercise, we will examine the code generated by gcc for functions that have
structures as arguments and return values, and from this see how these language
features are typically implemented.
The following C code has a function process having structures as argument
and return values, and a function eval that calls process:
*/

typedef struct {
    long a[2];
    long *p;
} strA;

typedef struct {
    long u[2];
    long q;
} strB;

strB process(strA s) {
    strB r;
    r.u[0] = s.a[1];
    r.u[1] = s.a[0];
    r.q = *s.p;
    return r;
}

long eval(long x, long y, long z) {
    strA s;
    s.a[0] = x;
    s.a[1] = y;
    s.p = &z;
    strB r = process(s);
    return r.u[0] + r.u[1] + r.q;
}

/*
Gcc generates the following code for these two functions:

strB process(strA s)

// RSP+24 : &Z
// RSP+16 : Y
// RSP+8  : X
// RSP    : RETURN ADDRESS
process:
    movq %rdi, %rax
    movq 24(%rsp), %rdx // RDX = &Z
    movq (%rdx), %rdx   // RDX = Z
    movq 16(%rsp), %rcx // RCX = Y
    movq %rcx, (%rdi)   // (RSP+72) = Y
    movq 8(%rsp), %rcx  // RCX = X
    movq %rcx, 8(%rdi)  // (RSP+80) = X
    movq %rdx, 16(%rdi) // (RSP+88) = Z
    ret


long eval(long x, long y, long z)
x in %rdi, y in %rsi, z in %rdx

eval:
    subq $104, %rsp     // allocate 104 bytes
    movq %rdx, 24(%rsp) // save z at rsp+24       (8)  (8)
    leaq 24(%rsp), %rax
    movq %rdi, (%rsp)   // s.a[0] = x;            (8)  (16)
    movq %rsi, 8(%rsp)  // s.a[1] = y;            (8)  (24)
    movq %rax, 16(%rsp) // s.p = &z;              (8)  (32)
    leaq 64(%rsp), %rdi // reserve rsp+64 for process
    call process
    movq 72(%rsp), %rax // r.u[0]
    addq 64(%rsp), %rax // + r.u[1]
    addq 80(%rsp), %rax // + r.q
    addq $104, %rsp     // deallocate 104 bytes
    ret

A. We can see on line 2 of function eval that it allocates 104 bytes on the stack.
Diagram the stack frame for eval, showing the values that it stores on the
stack prior to calling process.
// RSP    : X
// RSP+8  : Y
// RSP+16 : RSP+24
// RSP+24 : Z

B. What value does eval pass in its call to process?
// RSP+64

C. How does the code for process access the elements of structure argument s?
// relative to the provided address

D. How does the code for process set the fields of result structure r?
// fills 24 bytes starting with the provided address

E. Complete your diagram of the stack frame for eval, showing how eval
accesses the elements of structure r following the return from process.
// RSP    : X
// RSP+8  : Y
// RSP+16 : RSP+24
// RSP+24 : Z
// RSP+32 : 
// RSP+40 :
// RSP+48 :
// RSP+56 :
// RSP+64 : Y
// RSP+72 : X
// RSP+80 : Z
// RSP+88 :
// RSP+96 :
// RSP+104: RETURN ADDRESS

F. What general principles can you discern about how structure values are
passed as function arguments and how they are returned as function results?
// on the stack
*/
